name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - master

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run FedericoCarboni/setup-ffmpeg
      uses: ./
    - name: Run FedericoCarboni/setup-ffmpeg
      id: setup-ffmpeg
      uses: ./
    - run: ffmpeg -version
    - run: ffprobe -version
    # Install dependencies
    - name: System dependencies
      run: |
        apt-get update && apt-get install -y --no-install-recommends \
        texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra \
        ffmpeg
        pip install ghp-import
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install -r requirements.txt


    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html

